name: Umbraco Cloud Deployment Action
description:
  Deploy to Umbraco Cloud - uploads artifact, starts deployment, and monitors
  status in a single step
author: Matthew Hart

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: cloud
  color: blue

# Define your inputs here.
inputs:
  projectId:
    description: 'The Umbraco Cloud project ID'
    required: true
  apiKey:
    description: 'The Umbraco Cloud API key'
    required: true
  filePath:
    description: 'Path to the .cloudsource ZIP file to upload and deploy'
    required: true
  targetEnvironmentAlias:
    description:
      'The target environment alias to deploy to (e.g., dev, staging, prod)'
    required: true
  commitMessage:
    description: 'Commit message for the deployment'
    required: false
    default: 'Deployment from GitHub Actions'
  noBuildAndRestore:
    description: 'Skip build and restore steps'
    required: false
    default: 'false'
  skipVersionCheck:
    description: 'Skip version check'
    required: false
    default: 'false'
  timeoutSeconds:
    description: 'Timeout in seconds for deployment status checks'
    required: false
    default: '1200'
  description:
    description: 'Description for the artifact'
    required: false
  version:
    description: 'Version for the artifact'
    required: false
  baseUrl:
    description: 'Base URL for Umbraco Cloud API'
    required: false
    default: 'https://api.cloud.umbraco.com'
  base-branch:
    description: 'Base branch for pull request creation (defaults to main)'
    required: false
    default: 'main'
  upload-retries:
    description: 'Number of retry attempts for artifact upload (default: 3)'
    required: false
    default: '3'
  upload-retry-delay:
    description:
      'Base delay in milliseconds between upload retries (default: 10000)'
    required: false
    default: '10000'
  upload-timeout:
    description: 'Timeout in milliseconds for artifact upload (default: 60000)'
    required: false
    default: '60000'
  nuget-source-name:
    description: 'Name for the NuGet package source (optional)'
    required: false
  nuget-source-url:
    description: 'URL for the NuGet package source (optional)'
    required: false
  nuget-source-username:
    description: 'Username for NuGet package source authentication (optional)'
    required: false
  nuget-source-password:
    description: 'Password for NuGet package source authentication (optional)'
    required: false
  excluded-paths:
    description:
      'Comma-separated list of paths to exclude from artifacts. Paths are
      matched as prefixes (e.g., ".git/,.github/"). Use relative paths of the
      repository only, no ".." or absolute paths are allowed.'
    required: false
    default: '.git/,.github/'

# Define your outputs here.
outputs:
  artifactId:
    description: 'The artifact ID returned from the upload step'
  deploymentId:
    description: 'The deployment ID returned from the deployment step'
  deploymentState:
    description: 'The final deployment state (Completed, Failed, etc.)'
  deploymentStatus:
    description: 'The full deployment status response as JSON'
  changes:
    description: 'The changes (diff/patch) from the deployment'
  latest-completed-deployment-id:
    description: 'The latest completed deployment ID (when deployment fails)'
  pr-url:
    description: 'The URL of the created pull request (when deployment fails)'
  pr-number:
    description:
      'The number of the created pull request (when deployment fails)'
  nuget-source-status:
    description: 'Status of NuGet package source injection into artifact'

runs:
  using: node20
  main: dist/index.js
